-- Re-categorize the previously-imported 2026 balance-sheet expenses into the new,
-- more detailed categories (General Expenses, Debt Repayment, Partner Withdrawal
-- split by person). Safe to re-run: only touches rows still sitting in 'other'.
-- Matches by exact description+amount+date, which migration-expenses-2026-import.sql
-- inserted verbatim, so this is a precise 1:1 correction.

UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='AdmePro domain renewal' AND amount=1150.0 AND date='2026-01-03';
UPDATE expenses SET category='debt_repayment' WHERE type='out' AND category='other' AND description='Closing debt account of Shams 2025' AND amount=1143 AND date='2026-01-03';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Transport' AND amount=60.0 AND date='2026-01-04';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Water and sugar' AND amount=240.0 AND date='2026-01-05';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Fawry + Valu' AND amount=57148.0 AND date='2026-01-05';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Router installment month 12' AND amount=2000.0 AND date='2026-01-05';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Mic installment month 12' AND amount=2000.0 AND date='2026-01-05';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Vodafone month 12' AND amount=4452.0 AND date='2026-01-05';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Electricity' AND amount=867.0 AND date='2026-01-06';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Hard drive delivery' AND amount=155.0 AND date='2026-01-06';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Partner withdrawal (Malek)' AND amount=25000.0 AND date='2026-01-07';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Villa doorman — monthly' AND amount=200.0 AND date='2026-01-08';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Shady' AND amount=500.0 AND date='2026-01-08';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='File delivery courier' AND amount=300.0 AND date='2026-01-11';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Transport' AND amount=120.0 AND date='2026-01-11';
UPDATE expenses SET category='debt_repayment' WHERE type='out' AND category='other' AND description='Ahmed Barbary' AND amount=80000.0 AND date='2025-01-11';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal (Visa card)' AND amount=1500.0 AND date='2026-01-12';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Water' AND amount=360.0 AND date='2026-01-12';
UPDATE expenses SET category='debt_repayment' WHERE type='out' AND category='other' AND description='Mahmoud Shannah' AND amount=5000.0 AND date='2026-01-15';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Buffet' AND amount=394.0 AND date='2026-01-14';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Transport' AND amount=110.0 AND date='2026-01-18';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Transport' AND amount=160.0 AND date='2026-01-19';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Landline internet' AND amount=356.0 AND date='2026-01-19';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal' AND amount=50.0 AND date='2026-01-19';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Buffet' AND amount=509.0 AND date='2026-01-20';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal' AND amount=35000.0 AND date='2026-01-20';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Buffet' AND amount=1600.0 AND date='2026-01-21';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Carpet cleaning' AND amount=1050.0 AND date='2026-01-22';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Tax authority website subscription' AND amount=400.0 AND date='2026-01-22';
UPDATE expenses SET category='debt_repayment' WHERE type='out' AND category='other' AND description='Ahmed Barbary' AND amount=20000.0 AND date='2026-01-22';
UPDATE expenses SET category='debt_repayment' WHERE type='out' AND category='other' AND description='Mahmoud Shannah' AND amount=2500.0 AND date='2026-01-23';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Shoot transport for (Laila)' AND amount=1609.0 AND date='2026-01-23';
UPDATE expenses SET category='debt_repayment' WHERE type='out' AND category='other' AND description='Ahmed Barbary' AND amount=24000.0 AND date='2026-01-25';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='16TB Hard Drive' AND amount=16000.0 AND date='2026-01-25';
UPDATE expenses SET category='partner_radwa' WHERE type='out' AND category='other' AND description='Partner withdrawal' AND amount=50000.0 AND date='2026-01-25';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Transport' AND amount=300.0 AND date='2026-01-26';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Coffee' AND amount=135.0 AND date='2026-01-27';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Shady' AND amount=100.0 AND date='2026-01-27';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Transport' AND amount=115.0 AND date='2026-02-02';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Transport' AND amount=255.0 AND date='2026-02-03';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Coffee' AND amount=270.0 AND date='2026-02-03';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Buffet' AND amount=1800.0 AND date='2026-02-04';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Fawry + Valu' AND amount=66651.0 AND date='2026-02-05';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Router installment month1 (last month)' AND amount=2000.0 AND date='2026-02-05';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Mic installment month1 (last month)' AND amount=2000.0 AND date='2026-02-05';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Vodafone bill' AND amount=5000.0 AND date='2026-02-05';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='AdmePro hosting installment 1' AND amount=2049.0 AND date='2026-02-05';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Water' AND amount=360.0 AND date='2026-02-05';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Villa doorman — monthly' AND amount=200.0 AND date='2026-02-05';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal (Expenses)' AND amount=1000.0 AND date='2026-02-05';
UPDATE expenses SET category='debt_repayment' WHERE type='out' AND category='other' AND description='Mahmoud Shannah' AND amount=2500.0 AND date='2026-02-05';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Electricity' AND amount=1072.0 AND date='2026-02-05';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal (Visa card)' AND amount=1200.0 AND date='2026-02-11';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal' AND amount=21300.0 AND date='2026-02-11';
UPDATE expenses SET category='debt_repayment' WHERE type='out' AND category='other' AND description='Part of debt Abdelbaset 2025' AND amount=5000.0 AND date='2026-02-12';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Milk' AND amount=159.0 AND date='2026-02-15';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal' AND amount=10000.0 AND date='2026-02-15';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Fawry withdrawal fee' AND amount=3000.0 AND date='2026-02-15';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Transport' AND amount=320.0 AND date='2026-02-25';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Landline' AND amount=135.0 AND date='2026-03-02';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Order pickup' AND amount=225.0 AND date='2026-03-02';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Shams — mobile package top-up' AND amount=450.0 AND date='2026-03-02';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Villa doorman — monthly' AND amount=200.0 AND date='2026-03-02';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Transport' AND amount=120.0 AND date='2026-03-03';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal' AND amount=20000.0 AND date='2026-03-04';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Electricity' AND amount=2337.0 AND date='2026-03-05';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Valu & Fawry' AND amount=60552.0 AND date='2026-03-05';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Installment (1) Salaries — month 2' AND amount=13144.0 AND date='2026-03-05';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='AdmePro hosting installment 2' AND amount=2049.0 AND date='2026-03-05';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Installment (1) Timi + Shams & Shady Ramadan' AND amount=5975.0 AND date='2026-03-05';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Installment (1) Vodafone bill' AND amount=1400.0 AND date='2026-03-05';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='InstaPay transfer fee' AND amount=61.0 AND date='2026-03-05';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Transport' AND amount=259.0 AND date='2026-03-05';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Transport' AND amount=130.0 AND date='2026-03-08';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='InstaPay transfer fee' AND amount=25.0 AND date='2026-03-08';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Hard drive delivery — Nahla' AND amount=240.0 AND date='2026-03-08';
UPDATE expenses SET category='debt_repayment' WHERE type='out' AND category='other' AND description='Remaining debt Abdelbaset 2025' AND amount=5000.0 AND date='2026-03-08';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal' AND amount=200.0 AND date='2026-03-10';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Transport' AND amount=150.0 AND date='2026-03-10';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Hard drive pickup' AND amount=230.0 AND date='2026-03-12';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Hard drive handover — Nahla' AND amount=245.0 AND date='2026-03-15';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Company WE + landline internet renewal' AND amount=600.0 AND date='2026-03-16';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Freepik' AND amount=2000.0 AND date='2026-03-16';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal (the Farm)' AND amount=27000.0 AND date='2026-03-16';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Freepik' AND amount=1400.0 AND date='2026-03-18';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Eid gift — Shams & Shady' AND amount=2000.0 AND date='2026-03-18';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Tissues & coffee' AND amount=550.0 AND date='2026-03-24';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Water' AND amount=220.0 AND date='2026-03-24';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Transport' AND amount=200.0 AND date='2026-03-25';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Nodust' AND amount=310.0 AND date='2026-03-29';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal' AND amount=1600.0 AND date='2026-03-30';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Shams — mobile package' AND amount=450.0 AND date='2026-03-30';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Freepik' AND amount=3000.0 AND date='2026-03-30';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal (Token update Midestate)' AND amount=500.0 AND date='2026-03-31';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Transport' AND amount=189.0 AND date='2026-03-31';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Samples pickup' AND amount=125.0 AND date='2026-04-01';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Internet top-up' AND amount=396.0 AND date='2026-04-02';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Villa doorman — monthly' AND amount=200.0 AND date='2026-04-02';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal (inspection Midestate)' AND amount=6000.0 AND date='2026-04-05';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal' AND amount=1300.0 AND date='2026-04-05';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Transport' AND amount=200.0 AND date='2026-04-05';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Transport' AND amount=130.0 AND date='2026-04-05';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Transport' AND amount=189.0 AND date='2026-04-06';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Shoot transport for (Laila)' AND amount=1641.0 AND date='2026-04-06';
UPDATE expenses SET category='partner_radwa' WHERE type='out' AND category='other' AND description='Partner withdrawal' AND amount=25000.0 AND date='2026-04-06';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='InstaPay transfer fee' AND amount=62.0 AND date='2026-04-06';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Transport' AND amount=190.0 AND date='2026-04-07';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Transport' AND amount=290.0 AND date='2026-04-08';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Electricity' AND amount=1840.0 AND date='2026-04-08';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Buffet' AND amount=3040.0 AND date='2026-04-08';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal' AND amount=20000.0 AND date='2026-04-10';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal (Midestate)' AND amount=3000.0 AND date='2026-04-10';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Visa card' AND amount=1500.0 AND date='2026-04-12';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Freepik' AND amount=2400.0 AND date='2026-04-12';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Fawry + Valu' AND amount=61033.0 AND date='2026-04-12';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Installment (2) Salaries — month2' AND amount=13144.0 AND date='2026-04-12';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Installment (2) Timi & Shams & Shady Ramadan' AND amount=5975.0 AND date='2026-04-12';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Installment (2) Vodafone bill' AND amount=1400.0 AND date='2026-04-12';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Installment (1) Office expenses' AND amount=3000.0 AND date='2026-04-12';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Installment (3) Host' AND amount=2049.0 AND date='2026-04-12';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Vodafone bill' AND amount=3399.0 AND date='2026-04-12';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal' AND amount=1600.0 AND date='2026-04-12';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Landline internet bill' AND amount=396.0 AND date='2026-04-20';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Transport' AND amount=216.0 AND date='2026-04-20';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Freepik' AND amount=750.0 AND date='2026-04-20';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Sample delivery' AND amount=150.0 AND date='2026-04-20';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal' AND amount=800.0 AND date='2026-04-20';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Buffet' AND amount=1000.0 AND date='2026-04-22';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Freepik' AND amount=750.0 AND date='2026-04-22';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Vodafone bill' AND amount=3100.0 AND date='2026-04-23';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Freepik' AND amount=2000.0 AND date='2026-04-23';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Uber' AND amount=400.0 AND date='2026-04-27';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal (boxes + cartons + transport)' AND amount=1170.0 AND date='2026-04-27';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Shams — mobile package top-up' AND amount=450.0 AND date='2026-04-28';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal (Sicilia)' AND amount=400.0 AND date='2026-04-28';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal (printing + stamp + transport)' AND amount=1306.0 AND date='2026-04-28';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Freepik' AND amount=700.0 AND date='2026-04-28';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal (Expenses)' AND amount=1000.0 AND date='2026-04-28';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Buffet' AND amount=350.0 AND date='2026-04-28';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Transport' AND amount=120.0 AND date='2026-04-29';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Landline' AND amount=215.0 AND date='2026-04-29';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Water and milk' AND amount=470.0 AND date='2026-04-29';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Monay' AND amount=105.0 AND date='2026-04-29';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal' AND amount=200000.0 AND date='2026-04-29';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal' AND amount=500.0 AND date='2026-04-30';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Coffee beans' AND amount=100.0 AND date='2026-04-30';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal (RB bookstore tools)' AND amount=235.0 AND date='2026-04-30';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal (RB order delivery)' AND amount=90.0 AND date='2026-04-30';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal (FAB)' AND amount=6100.0 AND date='2026-04-30';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='WE internet top-up' AND amount=400.0 AND date='2026-04-03';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Villa doorman — monthly' AND amount=200.0 AND date='2026-04-03';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Milk' AND amount=175.0 AND date='2026-04-03';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal (RB order delivery)' AND amount=280.0 AND date='2026-05-03';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal' AND amount=200.0 AND date='2026-05-04';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Arabia delivery' AND amount=260.0 AND date='2026-05-04';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Adeeb' AND amount=90.0 AND date='2026-05-04';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Transport' AND amount=115.0 AND date='2026-05-04';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Fawry + Valu' AND amount=58721.0 AND date='2026-05-04';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Installment (3) Salaries — month2' AND amount=13144.0 AND date='2026-05-04';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Installment (3) Timi & Shams & Shady Ramadan' AND amount=5975.0 AND date='2026-05-04';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Installment (3) Vodafone bill' AND amount=1400.0 AND date='2026-05-04';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Installment (2) Office expenses' AND amount=3000.0 AND date='2026-05-04';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Freepik' AND amount=750.0 AND date='2026-05-04';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Freepik' AND amount=750.0 AND date='2026-05-05';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Coffee beans' AND amount=100.0 AND date='2026-05-05';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Transport — Tharwa' AND amount=120.0 AND date='2026-05-05';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Nescafe' AND amount=95.0 AND date='2026-05-05';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Electricity' AND amount=586.0 AND date='2026-05-06';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal RB' AND amount=5000.0 AND date='2026-05-06';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal' AND amount=15000.0 AND date='2026-05-06';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal RB' AND amount=1875.0 AND date='2026-05-09';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Buffet' AND amount=1178.0 AND date='2026-05-10';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Transport' AND amount=125.0 AND date='2026-05-10';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal' AND amount=7000.0 AND date='2026-05-11';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal RB' AND amount=500.0 AND date='2026-05-11';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal RB' AND amount=290.0 AND date='2026-05-12';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Freepik' AND amount=2000.0 AND date='2026-05-12';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal (Visa card)' AND amount=2000.0 AND date='2026-05-12';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal RB' AND amount=5500.0 AND date='2026-05-12';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal' AND amount=14250.0 AND date='2026-05-12';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Buffet' AND amount=630.0 AND date='2026-05-13';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Token update' AND amount=500.0 AND date='2026-05-14';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Transport' AND amount=340.0 AND date='2026-05-14';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Buffet' AND amount=3495.0 AND date='2026-05-17';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Freepik' AND amount=2000.0 AND date='2026-05-18';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal RB' AND amount=4600.0 AND date='2026-05-18';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Internet top-up' AND amount=447.0 AND date='2026-05-19';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal RB' AND amount=200.0 AND date='2026-05-21';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Shams — mobile package' AND amount=510.0 AND date='2026-05-21';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Vodafone bill' AND amount=5129.0 AND date='2026-05-21';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal (Part of account Abdelbaset Midestate)' AND amount=3000.0 AND date='2026-05-21';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal (Al-Hagga)' AND amount=90.0 AND date='2026-05-21';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Freepik' AND amount=750.0 AND date='2026-05-24';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Hard drive delivery — Nahla' AND amount=260.0 AND date='2026-05-24';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='AdmePro commercial register' AND amount=500.0 AND date='2026-05-25';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal (commercial register Midestate)' AND amount=500.0 AND date='2026-05-25';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Freepik' AND amount=1500.0 AND date='2026-05-25';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal (RB)' AND amount=2000.0 AND date='2026-06-01';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Higgsfield' AND amount=300.0 AND date='2026-06-01';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal (RB)' AND amount=10000.0 AND date='2026-06-01';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal (Installment)' AND amount=6300.0 AND date='2026-06-01';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal' AND amount=6000.0 AND date='2026-06-01';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Transport' AND amount=115.0 AND date='2026-06-02';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Villa doorman — monthly' AND amount=200.0 AND date='2026-06-02';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Water' AND amount=245.0 AND date='2026-06-03';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Coffee' AND amount=205.0 AND date='2026-06-03';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Freepik' AND amount=750.0 AND date='2026-06-04';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal' AND amount=5000.0 AND date='2026-06-08';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Fawry + Valu' AND amount=68500.0 AND date='2026-06-08';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Installment (3) Office expenses' AND amount=3000.0 AND date='2026-06-08';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal' AND amount=500.0 AND date='2026-06-08';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Milk' AND amount=360.0 AND date='2026-06-08';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Freepik' AND amount=700.0 AND date='2026-06-08';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Coffee beans — half kg' AND amount=450.0 AND date='2026-06-08';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Nescafe' AND amount=490.0 AND date='2026-06-09';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Hard drive pickup' AND amount=95.0 AND date='2026-06-09';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Freepik' AND amount=750.0 AND date='2026-06-09';
UPDATE expenses SET category='partner_radwa' WHERE type='out' AND category='other' AND description='Partner withdrawal' AND amount=25000.0 AND date='2026-06-09';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Electricity' AND amount=945.0 AND date='2026-06-09';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Internet top-up' AND amount=390.0 AND date='2026-06-10';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal (R B)' AND amount=4500.0 AND date='2026-06-10';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Transport' AND amount=100.0 AND date='2026-06-10';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal' AND amount=15000.0 AND date='2026-06-10';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Landline' AND amount=140.0 AND date='2026-06-11';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal (Visa card)' AND amount=1500.0 AND date='2026-06-11';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Freepik' AND amount=750.0 AND date='2026-06-11';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal (R B)' AND amount=2000.0 AND date='2026-06-11';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Freepik' AND amount=2500.0 AND date='2026-06-13';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Buffet' AND amount=1180.0 AND date='2026-06-15';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal (R B)' AND amount=2000.0 AND date='2026-06-15';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal (R B)' AND amount=2000.0 AND date='2026-06-16';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal (Abdelbaset Midestate)' AND amount=10000.0 AND date='2026-06-17';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Vodafone bill' AND amount=4300.0 AND date='2026-06-18';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='WE internet top-up' AND amount=450.0 AND date='2026-06-30';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Coffee beans' AND amount=100.0 AND date='2026-06-30';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal (Expenses)' AND amount=1500.0 AND date='2026-07-01';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Villa doorman — monthly' AND amount=200.0 AND date='2026-07-05';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Shams — mobile package top-up' AND amount=500.0 AND date='2026-07-05';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Water' AND amount=350.0 AND date='2026-07-05';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Transport' AND amount=100.0 AND date='2026-07-05';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal (RB)' AND amount=5500.0 AND date='2026-07-05';
UPDATE expenses SET category='partner_mostafa' WHERE type='out' AND category='other' AND description='Partner withdrawal (RB)' AND amount=6000.0 AND date='2026-07-05';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Coffee beans' AND amount=110.0 AND date='2026-07-06';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Electricity' AND amount=766.0 AND date='2026-07-06';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Freepik' AND amount=750.0 AND date='2026-07-06';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Freepik' AND amount=750.0 AND date='2026-07-09';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Hard drive pickup Nahla' AND amount=240.0 AND date='2026-07-08';
UPDATE expenses SET category='general' WHERE type='out' AND category='other' AND description='Hard drive pickup & delivery Nahla' AND amount=490.0 AND date='2026-07-09';
